RECURSE(
    draft
    extensions
    helpers
    iam
    iam_private
    resources
    ydb_common_client
    ydb_coordination
    ydb_datastreams
    ydb_discovery
    ydb_driver
    ydb_export
    ydb_extension
    ydb_federated_topic
    ydb_import
    ydb_monitoring
    ydb_operation
    ydb_params
    ydb_persqueue_core
    ydb_persqueue_public
    ydb_proto
    ydb_query
    ydb_rate_limiter
    ydb_result
    ydb_scheme
    ydb_table
    ydb_topic
    ydb_types
    ydb_value
)