cmake_minimum_required(VERSION 3.16)
project(ydb_qt_sql_upstream_tests LANGUAGES CXX)
set(CMAKE_AUTOMOC ON)
set(CMAKE_CXX_STANDARD 17)
find_package(Qt6 REQUIRED COMPONENTS Core Gui Sql Test Widgets)
set(SQL ${QT_SQL_SOURCE})
set(KERNEL qsql qsqldatabase qsqldriver qsqlquery qsqlthread)
set(MODELS qsqlquerymodel qsqlrelationaldelegate qsqlrelationaltablemodel qsqltablemodel)
foreach(TEST IN LISTS KERNEL MODELS)
  if("${TEST}" IN_LIST KERNEL)
    set(GROUP kernel)
  else()
    set(GROUP models)
  endif()
  add_executable(tst_${TEST} ${SQL}/${GROUP}/${TEST}/tst_${TEST}.cpp)
  target_link_libraries(tst_${TEST} PRIVATE Qt6::CorePrivate Qt6::Sql Qt6::SqlPrivate Qt6::Test)
endforeach()
target_link_libraries(tst_qsqlquerymodel PRIVATE Qt6::Gui Qt6::Widgets)
target_link_libraries(tst_qsqlrelationaldelegate PRIVATE Qt6::Widgets)
